Missing share.h include
This is needed at least on MinGW:
error: ‘_SH_DENYNO’ was not declared in this scope

Should also be on required : https://msdn.microsoft.com/en-us/library/febdfes5.aspx